apiVersion: v1
kind: Namespace
metadata:
  name: tenant-alpha
  labels:
    app.kubernetes.io/part-of: e2e-tests
    e2e-tenant: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-beta
  labels:
    app.kubernetes.io/part-of: e2e-tests
    e2e-tenant: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-gamma
  labels:
    app.kubernetes.io/part-of: e2e-tests
    e2e-tenant: "true"
