{{- if .Values.clusterSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-federation-proxy.fullname" . }}-kubeconfigs
  labels:
    {{- include "observability-federation-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.clusterSecrets.kubeconfigs }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
