{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-federation-proxy.fullname" . }}
  labels:
    {{- include "observability-federation-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  bearer-tokens: {{ join "," .Values.auth.bearerTokens | b64enc | quote }}
{{- end }}
